spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eleme_order?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://localhost:18000/eureka/,http://localhost:18001/eureka/,http://localhost:18002/eureka/"
